Added --mkdir option to freight-add.
This prevents the user from accidentally creating unwanted repositories, but
still allows to make them without looking at Freight's internals.

diff --git a/bin/freight-add b/bin/freight-add
--- a/bin/freight-add
+++ b/bin/freight-add
@@ -4,6 +4,7 @@
 
 #/ Usage: freight add [-c <conf>] [-v] [-h] <package> <manager>/<distro>...
 #/   -c <conf>, --conf=<conf> config file to parse
+#/   -d, --mkdir              create <manager>/<distro>, if it doesn't exist yet
 #/   -v, --verbose            verbose mode
 #/   -h, --help               show this help message
 
@@ -20,6 +21,7 @@ do
 		-c*) CONF="$(echo "$1" | cut -c"3-")" shift;;
 		--conf=*) CONF="$(echo "$1" | cut -c"8-")" shift;;
 		-v|--verbose) VERBOSE=1 shift;;
+		-d|--mkdir) MKDIR=1 shift;;
 		-h|--help) usage 0;;
 		-*) echo "# [freight] unknown switch: $1" >&2;;
 		*) break;;
@@ -74,6 +76,21 @@ add() {
     fi
 }
 
+# Create all the Freight library directories, if any is missing.
+[ "$MKDIR" = 1 ] && mkdir -p -- "$@"
+
+# Check if all the Freight library directories are present. If not, don't even
+# start any work.
+for DIRNAME in "$@"
+do
+	MISSING=
+	[ -d "$DIRNAME" ] || {
+		echo "# [freight] missing directory $DIRNAME" >&2
+		MISSING=1
+	}
+	[ "$MISSING" = "" ] || exit 1
+done
+
 # Hard link this package into every `<manager>/<distro>` given in `$@`.
 # These links will later be used to compile the `Release` and `Packages`
 # files in the Freight cache.
@@ -82,7 +99,6 @@ do
 	FILENAME="$(basename "$PATHNAME")"
 	for DIRNAME in "$@"
 	do
-		mkdir -p "$DIRNAME"
         case "$FILENAME" in
             *_*_*.deb) add "$FILENAME" "$DIRNAME" "$PATHNAME";;
             *.deb)
